apiVersion: apps/v1
kind: Deployment
metadata:
  name: watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watcher
  template:
    metadata:
      labels:
        app: watcher
    spec:
      containers:
      - args:
        - BTCUSD4
        - trade
        command:
        - python
        - run_socket.py
        envFrom:
        - configMapRef:
            name: watcher-config
        image: binance-watcher
        imagePullPolicy: Never
        name: watcher
