apiVersion: apps/v1
kind: Deployment
metadata:
  name: watcher
spec:
  selector:
   matchLabels:
    app: watcher
  replicas: 1
  template:
    metadata:
      labels:
        app: watcher
    spec:
      containers:
        - name: watcher
          image: binance-watcher
          command:
            - python
            - run_socket.py
          args:
            - symbol_pair
            - socket
          imagePullPolicy: "Never"
          envFrom:
            - configMapRef:
                name: watcher-config
            - configMapRef:
                name: postgres-config
